# Generated by Django 5.0.3 on 2024-03-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_employee_emp_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(help_text='Employee ID', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(help_text='Employee Name', max_length=30),
        ),
    ]
