# Generated by Django 5.0.1 on 2024-03-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_qrcodedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRCodeData',
        ),
    ]
