# Generated by Django 5.0.1 on 2024-03-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_issue_ticket_ticket_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='holiday_id',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
