# Generated by Django 5.0.1 on 2024-03-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_holiday_holiday_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='holiday_id',
            field=models.IntegerField(default=0),
        ),
    ]
