# Generated by Django 5.0.1 on 2024-03-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_holiday_id_alter_holiday_holiday_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='holiday_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
