# Generated by Django 5.0.1 on 2024-03-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_holiday_holiday_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='holiday_id',
        ),
        migrations.AddField(
            model_name='holiday',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
