# Generated by Django 5.0.1 on 2024-03-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_holiday_holiday_id_holiday_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_name', models.CharField(max_length=100)),
                ('E_Card_Link', models.CharField(max_length=100)),
                ('E_Assign_Date', models.DateField(max_length=100)),
                ('E_Mentor', models.CharField(max_length=100)),
                ('E_Priority', models.CharField(max_length=100)),
            ],
        ),
    ]
