# Generated by Django 5.0.1 on 2024-03-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_employee_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_task',
            name='E_Mentor',
            field=models.CharField(choices=[('Harsh Modi', 'Harsh Modi'), ('Kishan Patel', 'Kishan Patel'), ('Rahul Patel', 'Rahul Patel'), ('Harsh Sompura', 'Harsh Sompura'), ('Dhaval Gajjar', 'Dhaval Gajjar'), ('Vishal Tanna', 'Vishal Tanna'), ('Aakanksha Neliwer', 'Aakanksha Neliwer'), ('Bansari Goswami', 'Bansari Goswami'), ('Sandeep Makvana', 'Sandeep Makvana')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee_task',
            name='E_Priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], max_length=100),
        ),
    ]
