# Generated by Django 5.0.1 on 2024-03-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_in_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_out',
            name='approvel_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=50),
        ),
    ]
